export const mockRestaurants = [
  {
    _id: 'rest_001',
    name: 'Lumina Gourmet Bistro',
    tagline: 'Modern European & Artisanal Comfort Food',
    description: 'Experience sensory dining with locally sourced organic ingredients, wood-fired delights, and hand-crafted sauces.',
    cuisine: ['European', 'Artisanal', 'Italian'],
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    address: '450 Grand Avenue, Downtown',
    rating: 4.9,
    deliveryTime: '20-30 min',
    priceRange: '$$$',
    isAvailable: true,
  },
  {
    _id: 'rest_002',
    name: 'Sakura & Smoke Izakaya',
    tagline: 'Japanese Ramen, Yakitori & AI Fusion',
    description: 'Authentic 18-hour tonkotsu broth, charcoal-grilled skewers, and contemporary Japanese bowls.',
    cuisine: ['Japanese', 'Ramen', 'Asian Fusion'],
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    address: '88 Sakura Way, Midtown',
    rating: 4.8,
    deliveryTime: '25-35 min',
    priceRange: '$$',
    isAvailable: true,
  }
];

export const mockFoodItems = [
  {
    _id: 'food_001',
    restaurant: 'rest_001',
    name: 'Truffle Wild Mushroom Tagliatelle',
    description: 'Hand-rolled fresh pasta tossed in black truffle velvet sauce, wild chanterelles, and aged Parmigiano Reggiano.',
    price: 24.50,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281270?auto=format&fit=crop&w=800&q=80',
    tags: ['Vegetarian', 'Truffle', 'Chef Special'],
    calories: 680,
    isAvailable: true,
  },
  {
    _id: 'food_002',
    restaurant: 'rest_001',
    name: 'Crispy Wood-Fired Burrata Flatbread',
    description: 'Creamy Puglia burrata, heirloom cherry tomatoes, fresh basil pesto, and micro-greens on a crisp artisanal crust.',
    price: 18.00,
    category: 'Appetizers',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
    tags: ['Vegetarian', 'Artisanal'],
    calories: 520,
    isAvailable: true,
  },
  {
    _id: 'food_003',
    restaurant: 'rest_001',
    name: 'Valrhona Dark Chocolate Lava Cake',
    description: 'Decadent molten chocolate cake featuring 70% French dark cocoa served with Madagascar vanilla gelato.',
    price: 12.00,
    category: 'Desserts',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
    tags: ['Sweet', 'Dessert'],
    calories: 490,
    isAvailable: true,
  },
  {
    _id: 'food_004',
    restaurant: 'rest_002',
    name: 'Signature Black Garlic Tonkotsu Ramen',
    description: 'Rich pork bone broth infused with charred black garlic oil, tender chashu belly, nitamago egg, and bamboo shoots.',
    price: 19.50,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    tags: ['Ramen', 'Spicy', 'Chef Special'],
    calories: 750,
    isAvailable: true,
  },
  {
    _id: 'food_005',
    restaurant: 'rest_002',
    name: 'Charcoal Skewered Wagyu Beef Yakitori',
    description: 'Glazed A5 Wagyu beef skewers grilled over binchotan charcoal with sweet tare reduction and shichimi pepper.',
    price: 22.00,
    category: 'Appetizers',
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80',
    tags: ['Gluten-Free', 'Grill'],
    calories: 410,
    isAvailable: true,
  },
  {
    _id: 'food_006',
    restaurant: 'rest_002',
    name: 'Yuzu Sparkling Botanical Elixir',
    description: 'Refreshing sparkling yuzu juice blended with organic green tea, mint leaves, and elderflower syrup.',
    price: 7.50,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    tags: ['Refreshing', 'Vegan'],
    calories: 120,
    isAvailable: true,
  }
];

export const mockOrders = [
  {
    _id: 'ord_1001',
    customer: 'user_001',
    customerName: 'Sophia Martinez',
    customerEmail: 'user@savora.com',
    restaurant: { _id: 'rest_001', name: 'Lumina Gourmet Bistro' },
    items: [
      { foodItem: 'food_001', name: 'Truffle Wild Mushroom Tagliatelle', price: 24.50, quantity: 2 }
    ],
    totalAmount: 49.00,
    status: 'Preparing',
    paymentStatus: 'Paid',
    deliveryAddress: { street: '128 Ocean Avenue', city: 'Metropolis', zip: '10002' },
    specialNotes: 'Extra parmesan on the side please!',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    _id: 'ord_1002',
    customer: 'user_002',
    customerName: 'Marcus Wright',
    customerEmail: 'marcus@example.com',
    restaurant: { _id: 'rest_002', name: 'Sakura & Smoke Izakaya' },
    items: [
      { foodItem: 'food_004', name: 'Signature Black Garlic Tonkotsu Ramen', price: 19.50, quantity: 1 },
      { foodItem: 'food_006', name: 'Yuzu Sparkling Botanical Elixir', price: 7.50, quantity: 1 }
    ],
    totalAmount: 27.00,
    status: 'Out for Delivery',
    paymentStatus: 'Paid',
    deliveryAddress: { street: '55 Park Lane', city: 'Metropolis', zip: '10003' },
    specialNotes: 'Call upon arrival.',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    _id: 'ord_1003',
    customer: 'user_003',
    customerName: 'Elena Rostova',
    customerEmail: 'elena@example.com',
    restaurant: { _id: 'rest_001', name: 'Lumina Gourmet Bistro' },
    items: [
      { foodItem: 'food_002', name: 'Crispy Wood-Fired Burrata Flatbread', price: 18.00, quantity: 1 },
      { foodItem: 'food_003', name: 'Valrhona Dark Chocolate Lava Cake', price: 12.00, quantity: 2 }
    ],
    totalAmount: 42.00,
    status: 'Pending',
    paymentStatus: 'Paid',
    deliveryAddress: { street: '90 Riverside Dr', city: 'Metropolis', zip: '10005' },
    createdAt: new Date().toISOString(),
  }
];

export const mockReviews = [
  {
    _id: 'rev_001',
    restaurant: 'rest_001',
    customerName: 'Sophia Martinez',
    rating: 5,
    comment: 'The Truffle Tagliatelle was sublime! Arrived piping hot and rich in flavor. Outstanding quality.',
    aiSentiment: 'Positive',
    aiKeywords: ['Truffle Tagliatelle', 'Hot Delivery', 'Rich Flavor'],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    _id: 'rev_002',
    restaurant: 'rest_001',
    customerName: 'David K.',
    rating: 4,
    comment: 'Great burrata flatbread and chocolate lava cake. Delivery took slightly longer but food was superb.',
    aiSentiment: 'Positive',
    aiKeywords: ['Burrata Flatbread', 'Chocolate Lava Cake', 'Superb Food'],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    _id: 'rev_003',
    restaurant: 'rest_002',
    customerName: 'Sarah Jenkins',
    rating: 5,
    comment: 'The black garlic tonkotsu ramen is the best in the city. Perfectly tender chashu and rich broth!',
    aiSentiment: 'Positive',
    aiKeywords: ['Black Garlic Ramen', 'Tender Chashu', 'Best in City'],
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  }
];
