export const mockRestaurants = [
  {
    _id: 'rest_001',
    name: 'Maharaja Royal Indian Cuisine',
    tagline: 'Authentic North & South Indian Fine Dining',
    description: 'Experience regal Indian gastronomy featuring slow-cooked Mughlai curries, aromatic biryanis, and tandoori charcoal delicacies.',
    cuisine: ['North Indian', 'Mughlai', 'Biryani'],
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    address: '74 Park Street, Connaught Place',
    rating: 4.9,
    deliveryTime: '20-30 min',
    priceRange: '₹₹₹',
    isAvailable: true,
  },
  {
    _id: 'rest_002',
    name: 'Spice Symphony Tandoor Bistro',
    tagline: 'Clay-Oven Grills & Coastal Indian Delights',
    description: 'Fresh tandoori tikka, buttery naan breads, sizzling kebabs, and authentic South Indian dosa varieties.',
    cuisine: ['Tandoori', 'South Indian', 'Street Food'],
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    address: '12 MG Road, Indiranagar',
    rating: 4.8,
    deliveryTime: '25-35 min',
    priceRange: '₹₹',
    isAvailable: true,
  },
  {
    _id: 'rest_003',
    name: 'Mumbai Street Spice Co.',
    tagline: 'Authentic Chaat, Vada Pav & BOMBAY Street Delights',
    description: 'Crispy Pani Puri, Mumbai Vada Pav, Pav Bhaji cooked on large tawa, and sizzling Bhel Puri.',
    cuisine: ['Street Food', 'North Indian', 'Snacks'],
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=80',
    address: '45 Chowpatty Beach Road, Marine Drive',
    rating: 4.7,
    deliveryTime: '15-25 min',
    priceRange: '₹',
    isAvailable: true,
  },
  {
    _id: 'rest_004',
    name: 'Chennai Express Tiffin & Dosa Hub',
    tagline: 'Traditional South Indian Chettinad & Filter Coffee',
    description: 'Steaming hot idlis, crispy ghee roast dosas, vada dipping sambar, and authentic Kumbakonam filter coffee.',
    cuisine: ['South Indian', 'Breakfast'],
    image: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=1200&q=80',
    address: '88 Anna Salai, T. Nagar',
    rating: 4.9,
    deliveryTime: '15-25 min',
    priceRange: '₹',
    isAvailable: true,
  },
  {
    _id: 'rest_005',
    name: 'Peshawri Tandoor & Kebab Grill',
    tagline: 'Charcoal-Grilled Mughlai Kebabs & Rich Gravies',
    description: 'Succulent Galouti kebabs, fiery chicken tikka, Kashmiri rogan josh, and soft rumali roti.',
    cuisine: ['Tandoori', 'Mughlai', 'North Indian'],
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=1200&q=80',
    address: '22 Khan Market, New Delhi',
    rating: 4.9,
    deliveryTime: '30-40 min',
    priceRange: '₹₹₹',
    isAvailable: true,
  },
  {
    _id: 'rest_006',
    name: 'Punjab Da Dhaba & Paratha House',
    tagline: 'Rustic Highway Dhaba Flavors & Lassi',
    description: 'Amritsari Kulcha, Dal Makhani slow-cooked overnight, Sarson Ka Saag with Makki Roti, and thick sweet lassi.',
    cuisine: ['North Indian', 'Dhaba Style'],
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=1200&q=80',
    address: 'GT Road, Highway Milestone 42',
    rating: 4.8,
    deliveryTime: '20-35 min',
    priceRange: '₹₹',
    isAvailable: true,
  }
];

export const mockFoodItems = [
  {
    _id: 'food_001',
    restaurant: 'rest_001',
    name: 'Butter Chicken & Garlic Naan',
    description: 'Tender tandoori chicken simmered in rich velvet tomato butter gravy, served with fluffy garlic butter naan.',
    price: 380,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80',
    tags: ['Bestseller', 'Mughlai', 'Chef Special'],
    calories: 680,
    isAvailable: true,
  },
  {
    _id: 'food_002',
    restaurant: 'rest_001',
    name: 'Paneer Tikka Angara',
    description: 'Cottage cheese cubes marinated in spicy Kashmiri chili yogurt and smoked over charcoal tandoor.',
    price: 290,
    category: 'Appetizers',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80',
    tags: ['Vegetarian', 'Tandoori'],
    calories: 420,
    isAvailable: true,
  },
  {
    _id: 'food_003',
    restaurant: 'rest_001',
    name: 'Gulab Jamun with Saffron Rabri',
    description: 'Warm golden khoya dumplings soaked in rose cardamom syrup topped with thick creamy rabri.',
    price: 140,
    category: 'Desserts',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
    tags: ['Sweet', 'Dessert'],
    calories: 390,
    isAvailable: true,
  },
  {
    _id: 'food_004',
    restaurant: 'rest_002',
    name: 'Hyderabadi Zafrani Dum Biryani',
    description: 'Fragrant long-grain basmati rice layered with spiced cottage cheese/chicken, saffron, caramelized onions, and mint.',
    price: 340,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    tags: ['Biryani', 'Spicy', 'Chef Special'],
    calories: 720,
    isAvailable: true,
  },
  {
    _id: 'food_005',
    restaurant: 'rest_002',
    name: 'Crispy Masala Dosa Platter',
    description: 'Golden thin rice crepe filled with tempered potato masala, served with piping hot sambar and coconut chutney.',
    price: 180,
    category: 'Appetizers',
    image: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80',
    tags: ['South Indian', 'Vegan'],
    calories: 350,
    isAvailable: true,
  },
  {
    _id: 'food_006',
    restaurant: 'rest_002',
    name: 'Alphonso Mango Lassi',
    description: 'Chilled thick yogurt smoothie blended with sweet Alphonso mango pulp and cardamom powder.',
    price: 120,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    tags: ['Refreshing', 'Vegetarian'],
    calories: 210,
    isAvailable: true,
  },
  {
    _id: 'food_007',
    restaurant: 'rest_003',
    name: 'Mumbai Butter Pav Bhaji',
    description: 'Spicy mashed vegetable curry topped with generous Amul butter, served with soft toasted pavs and lemon.',
    price: 160,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    tags: ['Street Food', 'Bestseller', 'Vegetarian'],
    calories: 520,
    isAvailable: true,
  },
  {
    _id: 'food_008',
    restaurant: 'rest_003',
    name: 'Authentic Bombay Vada Pav (2 Pcs)',
    description: 'Spicy garlic potato fritter sandwiched in soft bakery bun with dry garlic chutney and fried green chili.',
    price: 90,
    category: 'Appetizers',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    tags: ['Bombay Classic', 'Spicy'],
    calories: 380,
    isAvailable: true,
  },
  {
    _id: 'food_009',
    restaurant: 'rest_003',
    name: 'Classic Pani Puri Platter (8 Pcs)',
    description: 'Crispy hollow puris filled with spiced potato chickpea mash, served with cold mint pani and sweet tamarind chutney.',
    price: 110,
    category: 'Appetizers',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    tags: ['Chaat', 'Street Food'],
    calories: 240,
    isAvailable: true,
  },
  {
    _id: 'food_010',
    restaurant: 'rest_004',
    name: 'Ghee Roast Masala Dosa',
    description: 'Crispy paper thin crepe roasted with fragrant desi ghee, stuffed with spiced potato masala, served with 3 chutneys.',
    price: 210,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=800&q=80',
    tags: ['South Indian', 'Ghee Roast', 'Chef Special'],
    calories: 460,
    isAvailable: true,
  },
  {
    _id: 'food_011',
    restaurant: 'rest_004',
    name: 'Steaming Button Idli Sambar Dip (10 Pcs)',
    description: 'Soft fluffy mini rice cakes submerged in hot aromatic Chettinad lentil sambar drizzled with ghee.',
    price: 150,
    category: 'Appetizers',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    tags: ['Healthy', 'Breakfast'],
    calories: 290,
    isAvailable: true,
  },
  {
    _id: 'food_012',
    restaurant: 'rest_004',
    name: 'Traditional Kumbakonam Filter Coffee',
    description: 'Authentic decoction coffee brewed with chicory and frothed in a brass tumbler.',
    price: 80,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    tags: ['Traditional', 'Hot Coffee'],
    calories: 120,
    isAvailable: true,
  },
  {
    _id: 'food_013',
    restaurant: 'rest_005',
    name: 'Royal Galouti Kebab with Paratha',
    description: 'Melt-in-mouth spiced minced mutton kebabs served with flaky saffron Mughlai paratha.',
    price: 360,
    category: 'Appetizers',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80',
    tags: ['Mughlai', 'Chef Special', 'Non-Veg'],
    calories: 580,
    isAvailable: true,
  },
  {
    _id: 'food_014',
    restaurant: 'rest_005',
    name: 'Kashmiri Mutton Rogan Josh',
    description: 'Slow-cooked tender mutton curry infused with rattan jot and rich aromatic Kashmiri whole spices.',
    price: 420,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&w=800&q=80',
    tags: ['Authentic', 'Royal Gravy'],
    calories: 640,
    isAvailable: true,
  },
  {
    _id: 'food_015',
    restaurant: 'rest_005',
    name: 'Garlic Butter Rumali Roti (3 Pcs)',
    description: 'Paper-thin soft hand-tossed breads baked over an inverted copper wok with garlic butter glaze.',
    price: 90,
    category: 'Sides',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    tags: ['Fresh Bread', 'Tandoori'],
    calories: 220,
    isAvailable: true,
  },
  {
    _id: 'food_016',
    restaurant: 'rest_006',
    name: 'Amritsari Stuffed Kulcha & Chole',
    description: 'Crispy layered clay-oven bread stuffed with spiced potato & cottage cheese, served with spicy chole curry.',
    price: 240,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    tags: ['Dhaba Special', 'Punjabi'],
    calories: 610,
    isAvailable: true,
  },
  {
    _id: 'food_017',
    restaurant: 'rest_006',
    name: 'Signature Dal Makhani',
    description: 'Whole black lentils slow-cooked overnight on charcoal coals with fresh white butter and heavy cream.',
    price: 280,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    tags: ['Bestseller', 'Creamy', 'Vegetarian'],
    calories: 510,
    isAvailable: true,
  },
  {
    _id: 'food_018',
    restaurant: 'rest_006',
    name: 'Kulhad Malai Lassi',
    description: 'Thick creamy sweetened churned yogurt served in traditional earthy clay kulhad topped with rabri layer.',
    price: 130,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    tags: ['Chilled', 'Punjabi Special'],
    calories: 280,
    isAvailable: true,
  }
];

export const mockOrders = [
  {
    _id: 'ord_1001',
    customer: 'user_001',
    customerName: 'Sophia Martinez',
    customerEmail: 'user@savora.com',
    restaurant: { _id: 'rest_001', name: 'Maharaja Royal Indian Cuisine' },
    items: [
      { foodItem: 'food_001', name: 'Butter Chicken & Garlic Naan', price: 380, quantity: 2 }
    ],
    totalAmount: 760,
    status: 'Preparing',
    paymentStatus: 'Paid',
    deliveryAddress: { street: '128 Ocean Avenue', city: 'Metropolis', zip: '10002' },
    specialNotes: 'Make it medium spicy please!',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    _id: 'ord_1002',
    customer: 'user_002',
    customerName: 'Marcus Wright',
    customerEmail: 'marcus@example.com',
    restaurant: { _id: 'rest_002', name: 'Spice Symphony Tandoor Bistro' },
    items: [
      { foodItem: 'food_004', name: 'Hyderabadi Zafrani Dum Biryani', price: 340, quantity: 1 },
      { foodItem: 'food_006', name: 'Alphonso Mango Lassi', price: 120, quantity: 1 }
    ],
    totalAmount: 460,
    status: 'Out for Delivery',
    paymentStatus: 'Paid',
    deliveryAddress: { street: '55 Park Lane', city: 'Metropolis', zip: '10003' },
    specialNotes: 'Include extra green chutney.',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    _id: 'ord_1003',
    customer: 'user_003',
    customerName: 'Elena Rostova',
    customerEmail: 'elena@example.com',
    restaurant: { _id: 'rest_001', name: 'Maharaja Royal Indian Cuisine' },
    items: [
      { foodItem: 'food_002', name: 'Paneer Tikka Angara', price: 290, quantity: 1 },
      { foodItem: 'food_003', name: 'Gulab Jamun with Saffron Rabri', price: 140, quantity: 2 }
    ],
    totalAmount: 570,
    status: 'Pending',
    paymentStatus: 'Paid',
    deliveryAddress: { street: '90 Riverside Dr', city: 'Metropolis', zip: '10005' },
    createdAt: new Date().toISOString(),
  }
];

export const mockReviews = [
  {
    _id: 'rev_001',
    restaurant: 'rest_001',
    customerName: 'Sophia Martinez',
    rating: 5,
    comment: 'The Butter Chicken and Garlic Naan were heavenly! Arrived piping hot and rich in spices. Outstanding quality.',
    aiSentiment: 'Positive',
    aiKeywords: ['Butter Chicken', 'Garlic Naan', 'Rich Spices'],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    _id: 'rev_002',
    restaurant: 'rest_001',
    customerName: 'David K.',
    rating: 5,
    comment: 'Sublime Paneer Tikka and Gulab Jamun! The tandoori charcoal smokiness was remarkable.',
    aiSentiment: 'Positive',
    aiKeywords: ['Paneer Tikka', 'Gulab Jamun', 'Charcoal Smoky'],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    _id: 'rev_003',
    restaurant: 'rest_002',
    customerName: 'Sarah Jenkins',
    rating: 5,
    comment: 'The Hyderabadi Dum Biryani is the best in town. Perfectly tender and aromatic saffron rice!',
    aiSentiment: 'Positive',
    aiKeywords: ['Zafrani Biryani', 'Aromatic Rice', 'Best in Town'],
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  }
];
